EXPERIMENT_NAME = "feedforward1"
VERBOSE = False
VISUALIZE = False
BOARD_SIZE = 11
NUMBER_OF_EPISODES = 1000 # actual games
NUMBER_OF_SIMULATIONS = 100 # MCTS simulations per move

# ANET
ANET_LEARNING_RATE = 0.01
ANET_NUM_HIDDEN_LAYERS = 7
ANET_NUM_HIDDEN_NODES = 100
ANET_ACTIVATION_FUNCTION = 'relu' # linear, sigmoid, tanh, relu
ANET_OPTIMIZER = 'adam' # adagrad, sgd, adam, rmsprop
ANET_M = 10 # number of ANETs to be cached 
ANET_BATCH_SIZE = 128

# TOPP
TOPP_NUM_GAMES_BETWEEN_ANY_TWO_PLAYERS = 100

# MCTS
MCTS_ROLLOUT_EPSILON = 0.25
MCTS_C = 1
